### ISSUE TITLE
Error saving changes

### ISSUE THREAD

**Issue by robertjf** [Matthew-Wise/Umbraco-CSP-manager#17]
When I go into CSP Manager and toggle "Enable" and/or "Report Only" on the Back Office configuration, I get an error:

![Screenshot 2023-01-11 at 10 27 15 am](https://user-images.githubusercontent.com/818101/211683445-8672fb9e-1a21-4f71-b37b-2ca51b6185cd.png)

Here are the related log entries:

```

Jan 11, 2023 10:27:09 AM | Error | e0b417f5fb32 | Exception ("d27a100f").
Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '='.
    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
    at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
    at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
    at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
    at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
    at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
    at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
 --- End of stack trace from previous location ---
    at NPoco.Database.ExecutionHookAsync[T](Func`1 action)
    at NPoco.Database.ExecuteNonQueryHelperAsync(DbCommand cmd)
    at NPoco.Database.ExecuteAsync(Sql Sql) ClientConnectionId:a018c7c6-5ab0-4cdf-8d6c-b5b74d119e8e Error Number:102,State:1,Class:15 ClientConnectionId before routing:9965174b-8ff7-46f9-b3b3-0044d3688f76 Routing Destination:e4363b91341a.tr5982.australiaeast1-a.worker.database.windows.net,11023


```

**Comment by Matthew-Wise** [comment]
Hi Robert, 
Firstly thank you for trying out the alpha. 

Can I ask is this using a MSSQL database and which version of Umbraco are you using?

**Comment by robertjf** [comment]
Hi Matthew,

Environment is:
* Azure Linux App Service
* Azure SQL Server database
* Umbraco 11.0.0

**Comment by Matthew-Wise** [comment]
Thanks for the report Robert, you will be glad to know I have an easy way to run the unit tests against MSSQL server locally at least and found the issue instantly :) 

I also took the oppurtunity to make the project multi targeted so now it will also be running .net7 for v11

https://www.nuget.org/packages/Umbraco.Community.CSPManager/1.0.1-alpha
