### ISSUE TITLE
Long Source Value Causes Sql Truncated Exception

### ISSUE THREAD

**Issue by paulsterling** [Matthew-Wise/Umbraco-CSP-manager#38]
First of all, thank you @Matthew-Wise for sharing this package! It is a great addition to our sites! #H5YR!

When we use a long (more than 255 characters) value for the source, a Sql Exception is thrown.

`Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated in table 'mycoolcspdb.dbo.CspDefinitionSource', column 'Source'. Truncated value: ''..."`

I'm assuming this is due to the length of the source string, but have not verified that is the case with the CSP-Manager source code.

**Versions**
Umbraco CMS 13.1.1
CSP Manager 1.2.0

**Log Entry**
```
Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated in table 'mycoolcspdb.dbo.CspDefinitionSource', column 'Source'. Truncated value: ''...our source here..."
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at NPoco.Database.ExecutionHookAsync[T](Func`1 action)
   at NPoco.Database.ExecuteNonQueryHelperAsync(DbCommand cmd)
   at NPoco.Database.InsertAsyncImp[T](PocoData pocoData, String tableName, String primaryKeyName, Boolean autoIncrement, T poco, Boolean sync)
   at NPoco.Database.SaveAsync[T](T poco)
   at Umbraco.Community.CSPManager.Services.CspService.SaveDefinitionAsync(IScope scope, CspDefinition definition)
   at Umbraco.Community.CSPManager.Services.CspService.SaveCspDefinitionAsync(CspDefinition definition)
   at Umbraco.Community.CSPManager.Controllers.CSPManagerApiController.SaveDefinition(CspDefinition definition)
   at lambda_method2731624(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
...removed connection info...
```

**Comment by Matthew-Wise** [comment]
Hi @paulsterling 
Sorry for the long delay in getting back to you on this.

Looks like a simple enough migration to increase the sql column length, will get this sorted. I should also probably add some validation :D

**Comment by Matthew-Wise** [comment]
New release fixing this is now out :D

**Comment by paulsterling** [comment]
Thanks @Matthew-Wise ! Have this deployed across all our sites now and can confirm the issue is fixed.
